version: '3.8'

services:
  # 👑 1. NESTJS BACKEND (Bizim Eklediğimiz Kısım)
  backend-api:
    build: . # Aynı klasördeki Dockerfile'ı kullanarak imajı üretir
    container_name: kampus_api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - kafka
    environment:
      # DİKKAT: localhost yerine konteyner isimlerini (postgres, redis, kafka) kullanıyoruz!
      - DATABASE_URL=postgres://postgres:beyza123@postgres:5432/kampus_dolap_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKER=kafka:9092
      # Varsa JWT_SECRET gibi diğer .env değişkenlerini de buraya eklemelisin.

  # 2. PostgreSQL (İlişkisel Veritabanı)
  postgres:
    image: postgres:16
    container_name: kampus_dolap_pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: beyza123
      POSTGRES_DB: kampus_dolap_db
    ports:
      - "5432:5432"
    volumes:
      - pg_new_data:/var/lib/postgresql/data

  # 3. Redis (Hız, Önbellek ve Socket.io adaptörü)
  redis:
    image: redis:alpine
    container_name: dolap_redis
    ports:
      - "6379:6379"

  # 4. Zookeeper (Kafka'nın Yönetimi için Şart)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: dolap_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # 5. Kafka (Mesaj Kuyruk Sistemi)
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: dolap_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  pg_new_data: